/**
 * 
 */
package vutshila.labs.bpelgen.core;

/**
 * @author Ernest Mashele <mashern@tuks.co.za>
 * 
 */
public interface VLConstants {

	// RODIN string constants
	final String EVENTB_ACCURATE = "org.eventb.core.accurate";
	final String EVENTB_CONTEXT = "org.eventb.core.scSeesContext";
	final String EVENTB_TARGET = "org.eventb.core.scTarget";

	// Context Translation
	final String TYPE = "Type";
	final String MESSAGE = "Message";
	final String EVENTB_TYPES[] = {};

	// BPEL generator
	final String GENERATED = "Generated by BPEL Generator plugin";
}
