/**
 *
 */
package za.vutshilalabs.bpelgen.core;

import org.eclipse.core.runtime.QualifiedName;

/**
 * @author Ernest Mashele <mashern@tuks.co.za>
 * 
 */
public interface IGlobalConstants {

	final String BPEL_EXTENSION = ".bpel";
	final String COLON_EQUALS = "\u2254";
	final String CONFIGURATION = "org.eventb.core.fwd";
	final String MINUS = "\u2212";

	// File extensions
	final String CONTEXT_EXTENSION = ".buc";
	// RODIN XML string constants
	final String EVENTB_ACCURATE = "org.eventb.core.accurate";

	final String EVENTB_SEES_CONTEXT = "org.eventb.core.scSeesContext";
	final String EVENTB_TARGET = "org.eventb.core.scTarget";

	// Corresponding primitive types
	// integer, natural, real number
	final String EVENTB_TYPES[] = { "\u2124", "\u2115", "\u211D" };
	// Comments
	final String GENERATED = "Generated by BPEL Generator plugin";

	final String MACHINE_EXTENSION = ".bum";
	final String MATH_ARROW = "\u2192";
	// Mathematical symbols
	final String MATH_ELEMENT = "\u2208";
	final String MESSAGE = "Message";

	final String NS = "http://docs.oasis-open.org/wsbpel/2.0/process/executable";
	final String PERIOD = ".";
	// Bpel default namespaces
	final String targetNS = "http://www.example.com/";
	// Translation
	final String TYPE = "Type";
	final String WSDL_EXTENSION = ".wsdl";

	final String XSD_TYPES[] = { "xs:int", "xs:nonNegativeInteger", "xs:double" };
	
	// extra property on resource about associated files.
	final QualifiedName CONTEXT = new QualifiedName("trans", "context");
	final QualifiedName MACHINE = new QualifiedName("trans", "machine");
	final QualifiedName WSDL = new QualifiedName("trans", "wsdl");
	final QualifiedName BPEL = new QualifiedName("trans", "bpel");
	final String TYPES[] = { "integer", "nonNegativeInteger", "double" };
	
}